version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  activiti-cloud-sso-idm:
    image: activiti/activiti-cloud-sso-idm:activiti-7-201709-EA
    ports:
      - "8180:8180"
  activiti-cloud-audit:
    image: activiti/activiti-cloud-audit:activiti-7-201709-EA
    links:
      - activiti-cloud-sso-idm:activiti-cloud-sso-idm
      - rabbitmq:rabbitmq
      - activiti-cloud-registry:activiti-cloud-registry
    environment:
      - ACT_AUDIT_PORT=8181
  activiti-cloud-query:
    image: activiti/activiti-cloud-query:activiti-7-201709-EA
    links:
      - activiti-cloud-sso-idm:activiti-cloud-sso-idm
      - rabbitmq:rabbitmq
      - activiti-cloud-registry:activiti-cloud-registry
    environment:
      - ACT_QUERY_PORT=8182
  activiti-cloud-registry:
    image: activiti/activiti-cloud-registry:activiti-7-201709-EA
    ports:
     - "8761:8761"
  activiti-cloud-gateway:
    image: activiti/activiti-cloud-gateway:activiti-7-201709-EA
    depends_on:
     - activiti-cloud-registry
    ports:
     - "8080:8080"
